### ISSUE TITLE
Is option "loose" passed correctly?

### ISSUE THREAD

**Issue by voronianski** [bkonkle/babel-preset-es2015-loose#1]
I'm wondering is option `loose: true` passed correctly to require?

Check your source code - https://github.com/bkonkle/babel-preset-es2015-loose/blob/master/index.js#L21

``` javascript
require("babel-plugin-transform-es2015-modules-commonjs", {loose: true}),
[require("babel-plugin-transform-regenerator"), { async: false, asyncGenerators: false }],
```

You pass options differently to these plugins..

**Why I'm asking?** The reason is that in my module I need `loose` option on `transform-es2015-classes` however using your plugin doesn't help me, but when I paste plugin directly into .babelrc loose works:

```
{
  "presets": [
    "es2015-loose",
    "react",
    "stage-0"
  ],
  "plugins": [
    "transform-es3-member-expression-literals",
    "transform-es3-property-literals",
    ["transform-es2015-classes", {"loose": true}] // now works
  ]
}
```

**Comment by bkonkle** [comment]
Thanks for the pull request! I've published the update to NPM.

**Comment by voronianski** [comment]
@bkonkle :+1:
