### ISSUE TITLE
Array spread with Sets seems broken.

### ISSUE THREAD

**Issue by apfelfabrik** [bkonkle/babel-preset-es2015-loose#10]
`Array` spread with `Set` seems broken. This prints `true` in `es2015`, and `false` in `es2015-loose`:

```
const a = new Set().add('stuff')
const content = [...a].pop()
console.log(typeof content === 'string')
```

Here is an [example on babeljs.io](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&code=%0A%2F%2F%20try%20this%20with%20es2015-loose%20enabled%20and%20disabled.%0A%0Aconst%20a%20%3D%20new%20Set%28%29.add%28'stuff'%29%0Aconst%20content%20%3D%20%5B...a%5D.pop%28%29%0Aconsole.log%28typeof%20content%20%3D%3D%3D%20'string'%29).

**Comment by chpio** [comment]
that's the whole point of the loose mode. you sacrifice es6 features/compatibility for better performance/less generated code.

**Comment by apfelfabrik** [comment]
You're right, this indeed seems to be the [documented behaviour](https://developit.github.io/babel-legacy-docs//docs/advanced/loose/):

> Loose mode enables certain transformers to generate cleaner output that lacks specific ES6 edgecases. These edgecases are either unlikely to appear in your code or the inclusion of them introduces significant overhead.
> As a result of loose mode code will execute faster and be much more readable and comparable to the original but will deviate from the spec in slight ways.

My assumption always was that transpiled code executes the same no matter the preset, but `loose` actually changes what the code does intentionally 😞
