### ISSUE TITLE
Ignoring root

### ISSUE THREAD

**Issue by uhtred** [bkonkle/babel-preset-es2015-loose#12]
When loading components outside webpack path, only don't find es2015-loose. es2015 works.

Maybe is ignoring resolve.root

**Comment by jimthedev** [comment]
https://github.com/developit/modify-babel-preset/issues/12

Could this be related?

**Comment by bkonkle** [comment]
Now that we've updated to the latest `modify-babel-preset`, can you tell me if this is still an issue?

Thanks!

**Comment by bkonkle** [comment]
I'm going to close this issue out. Feel free to reopen if you're still having trouble. 👍
