### ISSUE TITLE
Deprecate this package in favor of newest babel-preset-es2015

### ISSUE THREAD

**Issue by mrtnbroder** [bkonkle/babel-preset-es2015-loose#13]
newest babel-preset-es2015 offers a way to set a "loose" mode by itself, to this package can be deprecated :) https://github.com/babel/babel/tree/master/packages/babel-preset-es2015#options

**Comment by bkonkle** [comment]
I added a warning. Thanks!

**Comment by hzoo** [comment]
@bkonkle Did you deprecate the repo or the package on npm?

> npm deprecate my-thing@"< 0.2.3" "critical bug fixed in v0.2.3"`  

If you'd like, you can use https://docs.npmjs.com/cli/deprecate and just put what was in https://github.com/bkonkle/babel-preset-es2015-loose#this-project-is-deprecate

**Comment by bkonkle** [comment]
@hzoo Thanks! After some feedback, I decided to keep the project open, and only deprecate for those who have updated to Babel v6.13+. There are going to be a lot of people using lower versions of Babel for a long time. :-)
