### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by ai** [bkonkle/babel-preset-es2015-loose#7]
Commits is very hard to find breaking changes. I see a update from 6.x to 7.x, but I didn’t have a quick way to understand can I update it.

Here are th reasons why ChangeLog is very import for any project: http://keepachangelog.com/

Many ecosystems like PostCSS require ChangeLog in any packages.

**Comment by bkonkle** [comment]
Good point. I'll add one. Thanks!
