### ISSUE TITLE
Loose mode is 2x slower than es-2015

### ISSUE THREAD

**Issue by SaitoWu** [bkonkle/babel-preset-es2015-loose#9]
I have a `dump.es` file, which is very simple and easy:

``` javascript
let x = 1
```

When i compile with babel es-2015, it cost about `60ms`, but when i compile with es-2015-loose, it goes to about `150ms`

**Comment by bkonkle** [comment]
Hi! This package doesn't actually implement any of the loose mode optimizations - it's merely a preset that turns on the "loose" option in modules that support it. The actual performance of loose mode is something that you may want to open a ticket for on the actual plugins themselves - though I'd suggest searching for existing issues that are similar first.

Thanks!
